let startDate = "1908-10-09";
let endDate = "1911-05-12";

let people =
{
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-72.6850932, 41.7637111],
      },
      properties: {
          name: "Yung Wing",
          location: "Hartford, Connecticut",
          popupContent: `<img style='width:300px' src='res/yung-full.jpg'></img><br/><b style='font-size:1.5em'>Yung Wing</b><br/>First Chinese student to graduate from a United States university (Yale College in 1854). He was involved in business transactions between China and the United States and brought students from China to study in the United States on the Chinese Educational Mission. He became a naturalized American citizen, but his status was later revoked under the Naturalization Act of 1870`,
          icon: "res/yung.png",
          "marker-size": "large",
          "marker-symbol": "y",
          "marker-color": "#ace",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-118.243683,  34.052235],
      },
      properties: {
          name: "Charles Beach Boothe",
          location: "Los Angeles, California",
          popupContent: `<br/><img style='width:300px' src='res/boothe-full.jpg'></img><br/><b style='font-size:1.5em'>Charles Beach Boothe</b><br/>Wealthy lawyer, businessman, and former mayor of South Pasadena. Schoolmate of W.W. Allen.`,
          icon: "res/boothe.png",
          image: "res/boothe-full.jpg",
          "marker-size": "large",
          "marker-symbol": "b",
          "marker-color": "#bdf",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-117.243683,  33.052235],
      },
      properties: {
          name: "Homer Lea",
          location: "Los Angeles, California",
          popupContent: "<img style='width:300px' src='res/lea-full.jpg'></img><br/><b style='font-size:1.5em'>Homer Lea</b><br/>American adventurer, author and geopolitical strategist. Self-described general, but his knowledge was entirely based on irregular readings done at Stanford University. Military advisor to Sun Yat-sen in 1911-12.",
          icon: "res/lea.png",
          image: "res/lea-full.jpg",
          "marker-size": "large",
          "marker-symbol": "h",
          "marker-color": "#bdf",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [103.8198, 1.3521],
      },
      properties: {
          name: "Sun Yat-Sen",
          location: "Singapore",
          popupContent: "<img style='width:300px' src='res/sun-full.jpg'></img><br/><b style='font-size:1.5em'>Sun Yat-Sen</b><br/>Chinese physician, writer, philosopher, calligrapher. As the leader of the Tongmenhui and foremost pioneer of a Republican China, Sun is referred to as the 'Father of the Nation' in the ROC and the 'forerunner of democratic revolution' in the PRC.",
          icon: "res/sun.png",
          image: "res/sun-full.jpg",
          "marker-size": "large",
          "marker-symbol": "s",
          "marker-color": "#bdf",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [-74.0060, 40.7128],
      },
      properties: {
          name: "W.W. Allen",
          location: "New York",
          popupContent: "<b style='font-size:1.5em'>W.W. Allen</b><br/>A wealthy businessman, Allen had organised the Guggenheim Exploration Company and been associated for many years with some of the largest financial houses of New York and London. Acting as a consulting engineer for the League Club of New York City.",
          icon: "res/allen.png",
          image: "res/allen-full.png",
          "marker-size": "large",
          "marker-symbol": "a",
          "marker-color": "#bdf",
      },
    },
  ]
};

let locations = {
  "Sun Yat-sen": [1.3521,103.8198],
  "Yung Wing": [41.7637111, -72.6850932],
  "Charles Beach Boothe": [34.052235, -118.243683],
  "Homer Lea": [33.052235, -117.243683],
  "W.W. Allen": [40.7128, -74.0060],
};

let events = [
  {
    date:"1908-08-27",
    summary:"Outline of imperial consitution",
  },
  {
    date:"1908-10-14",
    summary:"Boothe and Yung meet in Hartford",
  },
  {
    date:"1908-11-14",
    summary:"Death of Guangxu Emperor",
  },
  {
    date:"1908-11-15",
    summary:"Death of Cixi",
  },
  {
    date:"1908-11-19",
    summary:"Army revolts in Anking and Canton suppressed"
  },
  {
    date:"1908-12-02",
    summary:"Puyi ascends throne",
  },
  {
    date:"1908-12-03",
    summary:"Imperial Court proclaims that  constitution and Parliament will become operative in 1916"
  },
  {
    date:"1908-12-25",
    summary:"Imperial Regent organizes a new palace guard under his direct command"
  },
  {
    date:"1909-01-01",
    summary:"Dismissal of Yuan Shi Kai",
  },
  {
    date:"1909-01-18",
    summary:"Allen and Yung meet in New York",
  },
  {
    date:"1909-02-17",
    summary:"Regent calls for  establishment of provincial assemblies by the end of the year"
  },
  {
    date:"1909-04-01",
    summary:"Provincial assembly elections (through April)"
  },
  {
    date:"1909-06-06",
    summary:"Four Powers consortium reaches a draft agreement on funding the Hukuang  Railroad"
  },
  {
    date:"1909-08-06",
    summary:"Female workers stirke in Shanghai"
  },
  {
    date:"1909-11-14",
    summary:"Provincial assemblies convene for the first time"
  },
  {
    date:"1909-12-29",
    summary:"Shanghai court  permanently closes the radical paper The People’s Sigh under Japanese pressure"
  },
  {
    date:"1910-01-26",
    summary:"Delegates to the Peking conference of provincial assemblies petition for an immediate parliament"
  },
  {
    date:"1910-01-30",
    summary:"Court rejects Peking petition"
  },
  {
    date:"1910-02-11",
    summary:"Attempted revolution by Sun Yat-sen in Canton - quickly defeated",
  },
  {
    date:"1910-02-12",
    summary:"1910 Chinese expedition to Tibet occupies Lhasa"
  },
  {
    date:"1910-04-15",
    summary:"Major rioting at Changsha in Hunan: rioters attack foreign businesses. Troops fire on demonstrators"
  },
  {
    date:"1910-05-09",
    summary:"The Imperial Court announces that National Assembly will convene in October; half of its members are to be appointed rather than elected"
  },
  {
    date:"1910-07-23",
    summary:"Boothe receives document of approval from Sun, signed by 18 Presidents of Chinese Provincial assemblies",
  },
  {
    date:"1910-06-05",
    summary:"1910 Nanyang industrial exposition",
  },
  {
    date:"1910-06-22",
    summary:"Second constitutionalist petition is submitted by provincial assemblies, signed by 300,000"
  },
  {
    date:"1910-06-27",
    summary:"Imperial Court rejects the second petition"
  },
  {
    date:"1910-07-21",
    summary:"Three Chinese native banks (正元, 兆康, 谦余) bankrupted in Shanghai Rubber Stock Market Crisis."
  },
  {
    date:"1910-08-04",
    summary:"Agreement with Four Powers Consortium for loan to Shanghai Taotai",
  },
  {
    date:"1910-10-03",
    summary:"National Assembly convenes"
  },
  {
    date:"1910-10-22",
    summary:"Imperial Court orders  Finance Ministry to prepare the first Chinese national budget"
  },
  {
    date:"1910-10-26",
    summary:"National Assembly urges that a responsible parliament be quickly convened"
  },
  {
    date:"1911-11-04",
    summary:"Imperial decree brings forward adoption of a constitution to 1913 from 1916"
  },
  {
    date:"1910-11-13",
    summary:"Penang Conference held by Sun Yat-sen (emergency conference of Tongmenhui on revolution)",
  },
  {
    date:"1911-03-24",
    summary:"Agreement with Japan for Chinese government 5% railway loan of 1911"
  },
  {
    date:"1911-04-29",
    summary:"Tsinghua university established",
  },
  {
    date:"1911-05-01",
    summary:"Loan from Four Power Consortium for railway construction"
  },
  {
    date:"1911-05-09",
    summary:"Qing edict ordering railway nationalisation",
  },
]

let letters = [
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-10-09",
    received: "1908-10-13",
    summary: "Asks to makes Boothe's acquaintance as Boothe is 'coming East'.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-10-21",
    received: "1908-12-23",
    summary: "Thanks Boothe for meeting.<br/>Discusses Japanese boycott in Hong and Canton.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-05",
    received: "1908-12-23",
    summary: "Approves conference of Boothe/Lea. Asks for their input on a political letter. <br/> Includes Hartford Courant article on death of Puyi.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Homer Lea",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Homer Lea"],
    sent: "1908-12-05",
    received: "1908-12-23",
    summary: "Approves conference of Boothe/Lea. Asks for input on a letter inviting heads of Chinese organisations to America. <br/> Includes Hartford Courant article on death of Puyi.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-06",
    received: "1908-12-23",
    summary: "Follow-up on December 5th letter. Explains role of provisional government.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-14",
    received: "1908-12-23",
    summary: "Update to plan from December 5th letter, suggesting approaching leaders individually.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1908-12-28",
    received: "1909-01-02",
    summary: "Reply to last three letters. Boothe has spoken with Lea. Both approve of Yung's plan. <br/> Financial backing will come from Allen, whom Wing should meet.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-04",
    received: "1909-01-16",
    summary: "Refers to 'astounding' dismissal of Yuan Shikai, and indicates 'we must eliminate Kang Youwei'.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-16",
    received: "1909-02-02",
    summary: "Expresses idea of recruiting Yuan Shikai. Reiterates dislike of Kang Youwei. Explains why he hasn't met Wing yet.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-01-16",
    received: "1909-01-21",
    summary: "Asks why Yung hasn't yet met Allen. Complains about difficulties of getting information on China.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-25",
    received: "1909-02-02",
    summary: "Explains his opinions on Yuan Shikai incident, suggesting Yuan is actually interested in Chinese reform and Kang is just a paper reformer.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-02-02",
    received: "1909-02-19",
    summary: "Acknowledges previous letter, suggests contacting Yuan Shikai.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-02-13",
    received: "1909-02-16",
    summary: "Comments on lack of progess between Allen and Yung. Suggests Yung come to LA to discuss if no further progress is made.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-19",
    received: "1909-02-27",
    summary: "Explains lack of progress. Says he can't come to LA. Requests $100,000 business venture involving his Son going to China.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-22",
    received: "1909-02-27",
    summary: "Follow-up on previous letter, further explaining $100,000 business venture, and its revolutionary elements.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-03-06",
    received: "1909-04-01",
    summary: "Reply to letters of 19th and 22nd February. Explains difficulty of procuring $100,000 for factory in China. Discusses removing Kang Youwei from Pao Wang Hwui.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-06-05",
    received: "1909-06-11",
    summary: "Apologises for long delay. Discusses his new plans to go to China to improve revolutionary plans. Mentions a possible visit.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-06-11",
    received: "1909-07-01",
    summary: "Discusses current reform efforts. Discusses rumour that the Regent has asked Yuan to kill himself. Refers to Kang Youwei's involvement in this plan. Mentions Lea's new book, 'The Valour of Ignorance'.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-09-14",
    received: "1090-09-21",
    summary: "Apologises again for silence, due to working on his autobiography. Discusses and denies a the New York Herald's claim that Yuan Shikai was recalled to viceroyality of Manchuria.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-10-02",
    received: "1909-10-07",
    summary: "Delay in reply because Boothe was 'at the seashore'. Mentions Allen's enthiusiasm over the plans. Asks Yung to visit.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-10-20",
    received: "1909-11-04",
    summary: "Suggests Japanese imperialism and control of Manchuria may lead to a great war.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1909-12-23",
    received: "1910-01-01",
    summary: "Has been trying to write a note for 2-3 weeks, but has been incorporating a company. Explains impossiblity of meeting Sun/Lea in New York.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Homer Lea",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Homer Lea"],
    sent: "1910-03-04",
    received: "1910-03-20", //TODO
    summary: "Acknowledges that Sun met Boothe and Lea in LA. Describes 'recent Canton affair' as 'an abortive effort'. Says loan of $1,500,000 will be needed before serious revolution is even plausible.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-03-04",
    received: "1910-03-08",
    summary: "Acknowledges that Sun met Boothe and Lea in LA. Describes 'recent Canton affair' as 'an abortive effort'. Says loan of $1,500,000 will be needed before serious revolution is even plausible.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Sun Yat-sen",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1910-02-16",
    received: "1910-03-01", //TODO
    summary: "Expresses concern about Canton effort. Argues more capital, administration, military and naval power are necessary.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Yung Wing",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Yung Wing"],
    sent: "1910-03-08",
    received: "1910-03-16",
    summary: "[Referred to in letters, not included in collection.]",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-03-16",
    received: "1910-03-28",
    summary: "Acknowledges letter of 8th March. Mentions meeting Sun to discuss finance soon.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-03-28",
    received: "1910-04-10",
    summary: "Details plan to negotiate a loan of $10,000,000.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-05-26",
    received: "1910-06-10",
    summary: "Asks how Boothe's plans with Lea are progressing.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-11-10",
    received: "1910-11-24",
    summary: "Discusses the government promise to create a parliament 2 years hence. He believes this is an effort to 'prolong the dynasty', and not democracy.",
  },
  {
    type: "letter",
    iconUrl: "res/letter-icon.png",
    from: "Yung Wing",
    to: "Charles Beach Boothe",
    fromLocation: locations["Yung Wing"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-11-10",
    received: "1910-11-24",
    summary: "Discusses the government promise to create a parliament 2 years hence. He believes this is an effort to 'prolong the dynasty', and not democracy.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1908-11-18",
    received: "1908-11-25",
    summary: "Discusses conference with General Lea and starting communication with Kang You Wei and Sun. Sends idea for a cipher to use.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-11-19",
    received: "1908-12-23", //TODO
    summary: "Sends his ideas about ciphers to Boothe.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-11-25",
    received: "1908-12-23", //TODO
    summary: "Feedback on ciphers sent on 18th.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-07",
    received: "1908-12-23", //TODO
    summary: "More careful examination of ciphers.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-18",
    received: "1908-12-23", //TODO
    summary: "[Referred to in letters, not included in collection.]", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1908-12-23",
    received: "1909-01-04",
    summary: "Note mentioning Yung's plans to write letters to heads of organisation.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1908-12-28",
    received: "1909-01-02",
    summary: "Introduces W.W. Allen to Yung Wing (unnamed for secrecy reasons), and his plans to send his son to China. Instructs them to meet."
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1908-12-28",
    received: "1909-01-04",
    summary: "[Referred to in letters, not included in collection.]",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-01-02",
    received: "1909-01-11",
    summary: "Describes death of emperor as irrelevant, leaving China in same situation. Says new regent is controlled by Yuan Shikai.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-04",
    received: "1909-01-25", //TODO
    summary: "Asks about regent's most recent actions. Says he will meet Yung Wing.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-06",
    received: "1909-01-25", //TODO
    summary: "Includes clippings about death of emperor.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-11",
    received: "1909-01-25", //TODO
    summary: "Comments on firing of Yuan Shikai, describing the regent as firing the man controlling him. Says Yung Wing has not yet replied.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-12",
    received: "1909-01-25", //TODO
    summary: "Says he's spoken with Yung's son. Describes the dismissal of Yuan as 'a stunning blow the cause of which is not at all understood.'",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-21",
    received: "1909-02-01",
    summary: "Key letter describing meeting with Yung. Describes Yuan Shikai as is in total control of army - could be very useful to rebellion. Describes Kang as doubtful. Describes Sun as the most reliable of all, having nearly taken Canton. Proposes $9,000,000 will be needed for project. Expresses concerns about Yung's character: 'dense ignorance'.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-01-25",
    received: "1909-01-30",
    summary: "Says he assumes Yung has met Allen, but doesn't yet know about it. Describes events of January as favourable to our cause.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-01-29",
    received: "1909-02-03",
    summary: "Describes another meeting with Yung. Believes that public opinion and secret societies will allow quick formation of popular just revolution. Suggests Yuan Shikai deposed for $50,000,000 loan request. Clipping about Emperor having smallpox.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-01",
    received: "1909-02-10", //TODO
    summary: "Follow-up to January 29th letter. Says favourable information about information about revolution will not have reached Yung in Hartford.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-02-03",
    received: "1909-02-11", //TODO
    summary: "Has received January 29th letter but not February 2nd follow-up. Expresses concerns about plan as a result. Attempts to convince Allen of Yung's good character.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-02-03",
    received: "1909-02-11",
    summary: "Reply to January 21st letter. Has spoken with Lea. Believes expected cost of $9,000,000 to be totally wrong, and actual value to be around $2,500,000. Talks about Lea's new book, and how it might get a preface from Roosevelt.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-06",
    received: "1909-02-13", //TODO
    summary: "Two letters. First is long update describing a failed attempt to get financial backing from J.P. Morgan, who will do dealings with any state, but not attempt to create a new one. Second contains a quick note on the first, that he imparted minimal information to J.P. Morgan.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-10",
    received: "1909-02-20", //TODO
    summary: "Encloses notes from Yung on 'Wants of China'. Expresses further concerns about Yung.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-11",
    received: "1909-02-21", //TODO
    summary: "Quick note to say he'll reply to letter of February 3rd soon.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-02-12",
    received: "1909-02-22", //TODO
    summary: "Reply to February 1st. Another attempt to persuade Boothe of the good character of Yung.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-02-13",
    received: "1909-02-23", //TODO
    summary: "Reply to letters of February 3rd and 6th. Discusses Kang Youwei's relationship with Yung. Further concerns about Yung's character.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-03-01",
    received: "1909-03-08",
    summary: "Mentions possibility of visit to Los Angeles. Includes clippings from New York Herald and Metropolitan Magazine.", //TODO
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-03-02",
    received: "1909-03-19",
    summary: "[Referred to in letters, not included in collection.]",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1909-03-19",
    received: "1909-03-27",
    summary: "Expresses confusion about delayed letter of March 2nd. Discusses Yung's recent business proposals.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-03-14",
    received: "1910-03-24",
    summary: "Expresses serious frustration at Yung, and the way the project is being handled in a Utopian, child-like manner. Essentially withdraws from the project in its present form.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Homer Lea",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Homer Lea"],
    sent: "1910-03-14",
    received: "1910-03-24",
    summary: "Expresses serious frustration at Yung, and the way the project is being handled in a Utopian, child-like manner. Essentially withdraws from the project in its present form.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1909-03-24",
    received: "1909-03-31",
    summary: "[Referred to in letters, not included in collection.]",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-03-31",
    received: "1910-04-07", //TODO
    summary: "Discusses Homer Lea's book.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-04-04",
    received: "1910-04-12",
    summary: "Refers to clipping about a bomb being found in Prince Regent's car. Says Sun must stop this sort of thing from occurring, because if it can be tied to Sun, all prospects of fundraising will fail. Asks Boothe to pass this on.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-07-12",
    received: "1910-07-14",
    summary: "Short dispatch to inform Boothe of the failure of a recent fundraising conference.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "W.W. Allen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["W.W. Allen"],
    sent: "1910-07-19",
    received: "1910-07-23",
    summary: "Describes the document sent by Sun, and describes how this proves the control and approval that Sun has in China. This should facilitate fundraising in New York.",
  },
  {
    type: "letter",
    iconUrl: "res/red-letter-icon.png",
    from: "W.W. Allen",
    to: "Charles Beach Boothe",
    fromLocation: locations["W.W. Allen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-07-23",
    received: "1910-07-30",
    summary: "Acknowledges Sun's document. Details current fundraising efforts.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Sun Yat-sen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1910-05-12",
    received: "1910-05-30",
    summary: "Originally sent to Honolulu, reaches Sun in Japan. Discusses meetings with General Lea. Asks Sun to keep Boothe informed at regular intervals. Tells him to strengthen non-state organisations in China.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-05-24",
    received: "1910-06-25",
    summary: "Note on his trip to Japan, including his Japan address.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-06-22",
    received: "1910-09-03",
    summary: "Says the minister of foreign affairs resents his presence in Japan, under pressure from Peking, so he will have to go to Singapore. Says he will stop premature movements in China (before full revolution if prepared and funded.) Mentions he will send a document signed by Presidents of Chinese provinces soon. This document, dated in March, arrives in mid-July.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Sun Yat-sen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1910-06-25",
    received: "1910-09-03",
    summary: "Sent to Japan, reaches Sun in Singapore. Expresses confusion about how to cable Sun in Japan. Asks Sun to send the document signed by the Presidents of Chinese provinces. This arrives in mid-July.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-07-16",
    received: "1910-09-26",
    summary: "Says he's moved to Singapore, provides Singapore address. Kang You Wei is also in Singapore",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-09-04",
    received: "1910-10-21",
    summary: "Summarises former letters in case they didn't arrive. Says he sent signed document long ago, and suspects it has arrived. Asks about the progress of the fundraising projects in the US. Requests advance of $50,000 for prepatory work. Says the position among the army in Canton has recovered from their last failed revolution. Refers to Mutiny in East Turkmenistan.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Sun Yat-sen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1910-09-26",
    received: "1910-11-08",
    summary: "Describes failure of fundraising in New York, due to instability in money market. Says he is still trying, and is determined to succeed. Says July 15th letter was 'considerably delayed in transmission'. Refers to possibility of Yuan Shikai being recalled.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Sun Yat-sen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1910-10-21",
    received: "1910-12-13",
    summary: "Reply to September 4th letter. Says he still hasn't succeeded in fundraising, but will cable as soon as he succeeds.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-11-08",
    received: "1910-12-13",
    summary: "Asks about failure of fundraising, and whether there's some other way the money might be raised.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1910-12-16",
    received: "1911-03-06",
    summary: "Says he didn't receive a cable, so he assumes the fundraising failed. Asks if Boothe can do anything for them by his own means, even a few hundred thousand dollars.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Sun Yat-sen",
    to: "Charles Beach Boothe",
    fromLocation: locations["Sun Yat-sen"],
    toLocation: locations["Charles Beach Boothe"],
    sent: "1911-03-06",
    received: "1911-04-12",
    summary: "Says he has been raising the necessary frunds from Chinese countrymen in East Asia and Canada, as Boothe wasn't able to raise the funds in time. Asks for the signed document back.",
  },
  {
    type: "letter",
    iconUrl: "res/yellow-letter-icon.png",
    from: "Charles Beach Boothe",
    to: "Sun Yat-sen",
    fromLocation: locations["Charles Beach Boothe"],
    toLocation: locations["Sun Yat-sen"],
    sent: "1911-04-12",
    received: "1911-05-12",
    summary: "Says he's pleased at Sun's success. Says he fears the document will be intercepted if sent by registered mail, so Sun should pick it up from LA.",
  },
];
